### ISSUE TITLE
Styles missing running on Mac

### ISSUE THREAD

**Issue by tinchoforever** [gerardobort/mongorilla#21]
I followed the steps on the readme for local install and also I've had run 'bower install' but the main screen looks like this.
Is there any step missing to have it fully functional?
<img src="http://i57.tinypic.com/ev43tx.png">
<img src="http://i61.tinypic.com/mb3big.png">
Thanks!

**Comment by gerardobort** [comment]
It seems that AdminLTE has changed again the place of its main files.  Please, try updating the links from the layout file in server/views.  Cheers

**Comment by tinchoforever** [comment]
Awesome that was the issue, I will made changes and submit the pull request.
